options = {'AUX': 'aux', 
 'Android Auto': 'android-auto',
 'Bluetooth': 'bluetooth',
 'CarPlay': 'apple-carplay',
 'USB': 'usb',
 'Автоматический корректор фар': 'automatic-lighting-control',
 'Адаптивный круиз-контроль': 'auto-cruise',
 'Активная подвеска': 'activ-suspension',
 'Активный усилитель руля': 'servo',
 'Алькантара (Материал салона)': 'alcantara',
 'Антиблокировочная система (ABS)': 'abs',
 'Антипробуксовочная система (ASR)': 'asr',
 'Аудиоподготовка': 'audiopreparation',
 'Аудиосистема': 'audiosystem-cd',
 'Аудиосистема Hi-Fi': 'music-super',
 'Аудиосистема с TV': 'audiosystem-tv',
 'Аэрография': 'airbrush',
 'Беспроводная зарядка для смартфона': 'wireless-charger',
 'Блокировка замков задних дверей': 'power-child-locks-rear-doors',
 'Бортовой компьютер': 'computer',
 'Бронированный кузов': 'armored',
 'Велюр (Материал салона)': 'velvet-seats',
 'Вентиляция задних сидений': 'rear-seat-heat-vent',
 'Вентиляция передних сидений': 'front-seats-heat-vent',
 'Газобаллонное оборудование': 'LPG',
 'Голосовое управление': 'voice-recognition',
 'Датчик давления в шинах': 'tyre-pressure',
 'Датчик дождя': 'rain-sensor',
 'Датчик проникновения в салон (датчик объема)': 'volume-sensor',
 'Датчик света': 'light-sensor',
 'Датчик усталости водителя': 'drowsy-driver-alert-system',
 'Декоративная подсветка салона': 'decorative-interior-lighting',
 'Декоративные молдинги': 'body-mouldings',
 'Декоративные накладки на педали': 'sport-pedals',
 'Диски 14': '14-inch-wheels',
 'Диски 15': '15-inch-wheels',
 'Диски 16': '16-inch-wheels',
 'Диски 17': '17-inch-wheels',
 'Диски 18': '18-inch-wheels',
 'Диски 19': '19-inch-wheels',
 'Диски 20': '20-inch-wheels',
 'Диски 21': '21-inch-wheels',
 'Диски 22': '22-inch-wheels',
 'Дистанционный запуск двигателя': 'remote-engine-start',
 'Дневные ходовые огни': 'drl',
 'Доводчик дверей': 'power-latching-doors',
 'Докатка': 'reduce-spare-wheel',
 'Запуск двигателя с кнопки': 'start-button',
 'Защита картера': 'engine-proof',
 'Иммобилайзер': 'immo',
 'Искусственная кожа (Материал салона)': 'eco-leather',
 'Камера 360°': '360-camera',
 'Камера задняя': 'rear-camera',
 'Камера передняя': 'front-camera',
 'Климат-контроль 1-зонный': 'climate-control-1',
 'Климат-контроль 2-зонный': 'climate-control-2',
 'Климат-контроль многозонный': 'multizone-climate-control',
 'Кожа (Материал салона)': 'leather',
 'Количество мест: 2': 'seats-2',
 'Количество мест: 4': 'seats-4',
 'Количество мест: 5': 'seats-5',
 'Количество мест: 6': 'seats-6',
 'Количество мест: 7': 'seats-7',
 'Комбинированный (Материал салона)': 'combo-interior',
 'Кондиционер': 'condition',
 'Крепление детского кресла (задний ряд) ISOFIX': 'isofix',
 'Крепление детского кресла (передний ряд) ISOFIX': 'isofix-front',
 'Круиз-контроль': 'cruise-control',
 'Ксеноновые/Биксеноновые фары': 'xenon',
 'Лазерные фары': 'laser-lights',
 'Ламинированные боковые стекла': 'laminated-safety-glass',
 'Легкосплавные диски': 'alloy-wheel-disks',
 'Люк': 'hatch',
 'Металлик': 'paint-metallic',
 'Мультимедиа система для задних пассажиров': 'entertainment-system-for-rear-seat-passengers',
 'Мультифункциональное рулевое колесо': 'multi-wheel',
 'Навигационная система': 'navigation',
 'Накладки на пороги': 'door-sill-panel',
 'Обвес кузова': 'body-kit',
 'Обогрев рулевого колеса': 'wheel-heat',
 'Омыватель фар': 'light-cleaner',
 'Отделка кожей рулевого колеса': 'wheel-leather',
 'Отделка кожей рычага КПП': 'leather-gear-stick',
 'Отделка потолка чёрной тканью': 'black-roof',
 'Открытие багажника без помощи рук': 'easy-trunk-opening',
 'Охлаждаемый перчаточный ящик': 'cooling-box',
 'Память передних сидений': 'seat-memory',
 'Память сиденья водителя': 'driver-seat-memory',
 'Панорамная крыша / лобовое стекло': 'panorama-roof',
 'Парктроник задний': 'park-assist-r',
 'Парктроник передний': 'park-assist-f',
 'Передний центральный подлокотник': 'front-centre-armrest',
 'Пневмоподвеска': 'air-suspension',
 'Подогрев задних сидений': 'rear-seats-heat',
 'Подогрев передних сидений': 'front-seats-heat',
 'Подрулевые лепестки переключения передач': 'steering-wheel-gear-shift-paddles',
 'Подушка безопасности водителя': 'airbag-driver',
 'Подушка безопасности для защиты коленей водителя': 'knee-airbag',
 'Подушка безопасности пассажира': 'airbag-passenger',
 'Подушки безопасности боковые': 'airbag-side',
 'Подушки безопасности боковые задние': 'airbag-rear-side',
 'Подушки безопасности оконные (шторки)': 'airbag-curtain',
 'Полноразмерное запасное колесо': 'spare-wheel',
 'Прикуриватель и пепельница': 'ashtray-and-cigarette-lighter',
 'Программируемый предпусковой отопитель': 'programmed-block-heater',
 'Проекционный дисплей': 'projection-display',
 'Противотуманные фары': 'ptf',
 'Регулировка передних сидений по высоте': 'passenger-seat-updown',
 'Регулировка руля по вылету': 'wheel-configuration2',
 'Регулировка руля по высоте': 'wheel-configuration1',
 'Регулировка сиденья водителя по высоте': 'driver-seat-updown',
 'Регулируемый педальный узел': 'adj-pedals',
 'Рейлинги на крыше': 'roof-rails',
 'Розетка 12V': '12v-socket',
 'Розетка 220V': '220v-socket',
 'Рулевая колонка с памятью положения': 'wheel-memory',
 'Светлый салон': 'light-interior',
 'Светодиодные фары': 'led-lights',
 'Сигнализация': 'alarm',
 'Сигнализация с обратной связью': 'feedback-alarm',
 'Сиденья с массажем': 'massage-seats',
 'Система «старт-стоп»': 'start-stop-function',
 'Система автоматической парковки': 'auto-park',
 'Система адаптивного освещения': 'adaptive-light',
 'Система выбора режима движения': 'drive-mode-sys',
 'Система доступа без ключа': 'keyless-entry',
 'Система контроля за полосой движения': 'lane-keeping-assist',
 'Система контроля слепых зон': 'blind-spot',
 'Система ночного видения': 'night-vision',
 'Система помощи при спуске': 'dha',
 'Система помощи при старте в гору (HSA)': 'hcc',
 'Система помощи при торможении (BAS, EBD)': 'bas',
 'Система предотвращения столкновения': 'collision-prevention-assist',
 'Система распознавания дорожных знаков': 'traffic-sign-recognition',
 'Система стабилизации (ESP)': 'esp',
 'Система стабилизации рулевого управления (VSM)': 'vsm',
 'Система управления дальним светом': 'high-beam-assist',
 'Складной столик на спинках передних сидений': 'folding-tables-rear',
 'Складывающееся заднее сиденье': 'seat-transformation',
 'Солнцезащитная шторка на заднем стекле': 'roller-blind-for-rear-window',
 'Солнцезащитные шторки в задних дверях': 'roller-blinds-for-rear-side-windows',
 'Спортивная подвеска': 'sport-suspension',
 'Спортивные передние сиденья': 'sport-seats',
 'Стальные диски': 'steel-wheels',
 'Ткань (Материал салона)': 'fabric-seats',
 'Тонированные стекла': 'tinted-glass',
 'Третий задний подголовник': 'third-rear-headrest',
 'Третий ряд сидений': 'third-row-seats',
 'Тёмный салон': 'dark-interior',
 'Усилитель руля': 'wheel-power',
 'Фаркоп': 'turnbuckle',
 'Функция складывания спинки сиденья пассажира': 'folding-front-passenger-seat',
 'Центральный замок': 'lock',
 'ЭРА-ГЛОНАСС': 'glonass',
 'Электронная приборная панель': 'electronic-gage-panel',
 'Электрообогрев боковых зеркал': 'mirrors-heat',
 'Электрообогрев зоны стеклоочистителей': 'windcleaner-heat',
 'Электрообогрев лобового стекла': 'windscreen-heat',
 'Электрообогрев форсунок стеклоомывателей': 'heated-wash-system',
 'Электропривод зеркал': 'electro-mirrors',
 'Электропривод крышки багажника': 'electro-trunk',
 'Электрорегулировка задних сидений': 'electro-rear-seat',
 'Электрорегулировка передних сидений': 'passenger-seat-electric',
 'Электрорегулировка руля': 'e-adjustment-wheel',
 'Электрорегулировка сиденья водителя': 'driver-seat-electric',
 'Электроскладывание зеркал': 'auto-mirrors',
 'Электростеклоподъёмники задние': 'electro-window-back',
 'Электростеклоподъёмники передние': 'electro-window-front',
 'Яндекс.Авто': 'ya-auto'
}

colors = {
    'FAFBFB': 'white',
    'белый': 'white',
    '040001': 'black',
    'чёрный': 'black',
    'CACECB': 'silver',
    'серебристый': 'silver',
    '007F00': 'green',
    'зелёный': 'green',
    '660099': 'purple',
    'пурпурный': 'purple',
    '0000CC': 'navy_blue',
    'синий': 'navy_blue',
    'EE1D19': 'red',
    'красный': 'red',
    '200204': 'brown',
    'коричневый': 'brown',
    '97948F': 'gray',
    'серый': 'gray',
    'DEA522': 'golden',
    'золотистый': 'golden',
    'C49648': 'beige',
    'бежевый': 'beige',
    'FF8649': 'orange',
    'оранжевый': 'orange',
    '4A2197': 'violet',
    'фиолетовый': 'violet',
    '22A0F8': 'blue',
    'голубой': 'blue',
    'FFD600': 'yellow',
    'жёлтый': 'yellow'
}